version: '3.8'

services:
  postgres:
    container_name: aragon-postgres
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-dev}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-devpassword}
      POSTGRES_DB: ${POSTGRES_DB:-aragon_dev}
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-dev}']
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - aragon-network

networks:
  aragon-network:
    driver: bridge

volumes:
  db_data:
